cross_target_platform:
  - linux-64                            # [linux]
  - linux-aarch64                       # [linux]
  - linux-ppc64le                       # [linux]
  - osx-64                              # [linux64 or osx]
  - osx-arm64                           # [linux64 or osx]
  - win-64                              # [linux64 or (osx and x86_64) or win64]
rust_arch:
  - x86_64-unknown-linux-gnu            # [linux]
  - aarch64-unknown-linux-gnu           # [linux]
  - powerpc64le-unknown-linux-gnu       # [linux]
  - x86_64-apple-darwin                 # [linux64 or osx]
  - aarch64-apple-darwin                # [linux64 or osx]
  - x86_64-pc-windows-msvc              # [linux64 or (osx and x86_64) or win64]
rust_arch_env_build:
  - X86_64_UNKNOWN_LINUX_GNU            # [linux64]
  - AARCH64_UNKNOWN_LINUX_GNU           # [aarch64]
  - POWERPC64LE_UNKNOWN_LINUX_GNU       # [ppc64le]
  - X86_64_APPLE_DARWIN                 # [osx and x86_64]
  - AARCH64_APPLE_DARWIN                # [osx and arm64]
  - X86_64_PC_WINDOWS_MSVC              # [win64]
rust_arch_env:
  - X86_64_UNKNOWN_LINUX_GNU            # [linux]
  - AARCH64_UNKNOWN_LINUX_GNU           # [linux]
  - POWERPC64LE_UNKNOWN_LINUX_GNU       # [linux]
  - X86_64_APPLE_DARWIN                 # [linux64 or osx]
  - AARCH64_APPLE_DARWIN                # [linux64 or osx]
  - X86_64_PC_WINDOWS_MSVC              # [linux64 or (osx and x86_64) or win64]
rust_default_cc_build:
  - x86_64-conda-linux-gnu-cc           # [linux64]
  - aarch64-conda-linux-gnu-cc          # [aarch64]
  - powerpc64le-conda-linux-gnu-cc      # [ppc64le]
  - x86_64-apple-darwin13.4.0-clang     # [osx and x86_64]
  - arm64-apple-darwin20.0.0-clang      # [osx and arm64]
  - clang-cl                            # [win64]
rust_default_cc:
  - x86_64-conda-linux-gnu-cc           # [linux]
  - aarch64-conda-linux-gnu-cc          # [linux]
  - powerpc64le-conda-linux-gnu-cc      # [linux]
  - x86_64-apple-darwin13.4.0-clang     # [linux64 or osx]
  - arm64-apple-darwin20.0.0-clang      # [linux64 or osx]
  - clang-cl                            # [linux64 or (osx and x86_64) or win64]

# This should be max(build_platform_ver, cross_target_platform_ver)
MACOSX_SDK_VERSION:
  - 0                                   # [linux]
  - 0                                   # [linux]
  - 0                                   # [linux]
  - 10.9                                # [linux64 or osx]
  - 11.0                                # [linux64 or osx]
  - 0                                   # [linux64 or win64]
  # For osx-64 -> win-64 cross-compiling, set SDK version for the build system
  - 10.9                                # [osx and x86_64]
# This should match cross_target_platform_ver
MACOSX_DEPLOYMENT_TARGET:
  - 0                                   # [linux]
  - 0                                   # [linux]
  - 0                                   # [linux]
  - 10.9                                # [linux64 or osx]
  - 11.0                                # [linux64 or osx]
  - 0                                   # [linux64 or win64]
  # For osx-64 -> win-64 cross-compiling, set deployment target for the build system
  - 10.9                                # [osx and x86_64]
version:
  - 1.58.1
channel_sources:
  - conda-forge
  # - conda-forge/label/rust_dev,conda-forge
channel_targets:
  - conda-forge main
  # - conda-forge rust_dev
zip_keys:
  - - cross_target_platform
    - rust_arch
    - rust_arch_env
    - rust_default_cc
    - MACOSX_SDK_VERSION
    - MACOSX_DEPLOYMENT_TARGET
  - - version
    - channel_sources
    - channel_targets
