# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

name: Build conda package
on:
  push:

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.CONFIG }}
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      max-parallel: 50
      matrix:
        include:
          - CONFIG: linux_64_channel_targetsconda-forge_maincross_target_platformlinux-64rust_archx86_64-unknown-linux-gnurust_arch_envX86_64_UNKNOWN_LINUX_GNUrust_default_ccx86_64-_h8f9f3a8f
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_channel_targetsconda-forge_maincross_target_platformlinux-aarch64rust_archaarch64-unknown-linux-gnurust_arch_envAARCH64_UNKNOWN_LINUX_GNUrust_default_cc_h508ce537
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_channel_targetsconda-forge_maincross_target_platformlinux-ppc64lerust_archpowerpc64le-unknown-linux-gnurust_arch_envPOWERPC64LE_UNKNOWN_LINUX_GNUrust_de_h2822bb9f
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_channel_targetsconda-forge_maincross_target_platformosx-64rust_archx86_64-apple-darwinrust_arch_envX86_64_APPLE_DARWINrust_default_ccx86_64-apple-darwin_h0883ff80
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_channel_targetsconda-forge_maincross_target_platformosx-arm64rust_archaarch64-apple-darwinrust_arch_envAARCH64_APPLE_DARWINrust_default_ccarm64-apple-da_h4cd4fe54
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_channel_targetsconda-forge_maincross_target_platformwin-64rust_archx86_64-pc-windows-msvcrust_arch_envX86_64_PC_WINDOWS_MSVCrust_default_ccclang-cltarge_h8c7601a9
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_channel_targetsconda-forge_rust_devcross_target_platformlinux-64rust_archx86_64-unknown-linux-gnurust_arch_envX86_64_UNKNOWN_LINUX_GNUrust_default_ccx86_h67cb120d
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_channel_targetsconda-forge_rust_devcross_target_platformlinux-aarch64rust_archaarch64-unknown-linux-gnurust_arch_envAARCH64_UNKNOWN_LINUX_GNUrust_defaul_h099f7c26
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_channel_targetsconda-forge_rust_devcross_target_platformlinux-ppc64lerust_archpowerpc64le-unknown-linux-gnurust_arch_envPOWERPC64LE_UNKNOWN_LINUX_GNUrus_h31ae193d
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_channel_targetsconda-forge_rust_devcross_target_platformosx-64rust_archx86_64-apple-darwinrust_arch_envX86_64_APPLE_DARWINrust_default_ccx86_64-apple-da_h66be6056
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_channel_targetsconda-forge_rust_devcross_target_platformosx-arm64rust_archaarch64-apple-darwinrust_arch_envAARCH64_APPLE_DARWINrust_default_ccarm64-appl_h158b44a6
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_channel_targetsconda-forge_rust_devcross_target_platformwin-64rust_archx86_64-pc-windows-msvcrust_arch_envX86_64_PC_WINDOWS_MSVCrust_default_ccclang-clt_h8c389c05
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_channel_targetsconda-forge_maincross_target_platformlinux-64rust_archx86_64-unknown-linux-gnurust_arch_envX86_64_UNKNOWN_LINUX_GNUrust_default_ccx8_haae38bd7
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_channel_targetsconda-forge_maincross_target_platformlinux-aarch64rust_archaarch64-unknown-linux-gnurust_arch_envAARCH64_UNKNOWN_LINUX_GNUrust_defau_h17f56b5b
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_channel_targetsconda-forge_maincross_target_platformlinux-ppc64lerust_archpowerpc64le-unknown-linux-gnurust_arch_envPOWERPC64LE_UNKNOWN_LINUX_GNUru_he3a11d21
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_channel_targetsconda-forge_rust_devcross_target_platformlinux-64rust_archx86_64-unknown-linux-gnurust_arch_envX86_64_UNKNOWN_LINUX_GNUrust_default__h997b638a
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_channel_targetsconda-forge_rust_devcross_target_platformlinux-aarch64rust_archaarch64-unknown-linux-gnurust_arch_envAARCH64_UNKNOWN_LINUX_GNUrust_d_h48a02e5f
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_channel_targetsconda-forge_rust_devcross_target_platformlinux-ppc64lerust_archpowerpc64le-unknown-linux-gnurust_arch_envPOWERPC64LE_UNKNOWN_LINUX_G_hab40ff0b
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_ppc64le_channel_targetsconda-forge_maincross_target_platformlinux-64rust_archx86_64-unknown-linux-gnurust_arch_envX86_64_UNKNOWN_LINUX_GNUrust_default_ccx8_he7768dc3
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_ppc64le_channel_targetsconda-forge_maincross_target_platformlinux-aarch64rust_archaarch64-unknown-linux-gnurust_arch_envAARCH64_UNKNOWN_LINUX_GNUrust_defau_h993494b3
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_ppc64le_channel_targetsconda-forge_maincross_target_platformlinux-ppc64lerust_archpowerpc64le-unknown-linux-gnurust_arch_envPOWERPC64LE_UNKNOWN_LINUX_GNUru_hfc175dc8
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_ppc64le_channel_targetsconda-forge_rust_devcross_target_platformlinux-64rust_archx86_64-unknown-linux-gnurust_arch_envX86_64_UNKNOWN_LINUX_GNUrust_default__h50f73450
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_ppc64le_channel_targetsconda-forge_rust_devcross_target_platformlinux-aarch64rust_archaarch64-unknown-linux-gnurust_arch_envAARCH64_UNKNOWN_LINUX_GNUrust_d_h1520fd65
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_ppc64le_channel_targetsconda-forge_rust_devcross_target_platformlinux-ppc64lerust_archpowerpc64le-unknown-linux-gnurust_arch_envPOWERPC64LE_UNKNOWN_LINUX_G_hd23108f9
            STORE_BUILD_ARTIFACTS: False
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['ubuntu-latest']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
    steps:

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Build on Linux
      id: build-linux
      if: matrix.os == 'ubuntu'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
        CI: github_actions
        CONDA_FORGE_DOCKER_RUN_ARGS: "${{ matrix.CONDA_FORGE_DOCKER_RUN_ARGS }}"
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        if [[ "$(uname -m)" == "x86_64" ]]; then
          echo "::group::Configure binfmt_misc"
          docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
        fi
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        echo "::endgroup::"
        ./.scripts/run_docker_build.sh

    - name: Build on macOS
      id: build-macos
      if: matrix.os == 'macos'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        CI: github_actions
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        ./.scripts/run_osx_build.sh

    - name: Build on windows
      id: build-windows
      if: matrix.os == 'windows'
      shell: cmd
      run: |
        set "flow_run_id=github_%GITHUB_RUN_ID%"
        set "remote_url=https://github.com/%GITHUB_REPOSITORY%"
        set "sha=%GITHUB_SHA%"
        call ".scripts\run_win_build.bat"
      env:
        # default value; make it explicit, as it needs to match with artefact
        # generation below. Not configurable for now, can be revisited later
        CONDA_BLD_PATH: C:\bld
        MINIFORGE_HOME: ${{ contains(runner.arch, 'ARM') && 'C' || 'D' }}:\Miniforge
        PYTHONUNBUFFERED: 1
        CONFIG: ${{ matrix.CONFIG }}
        CI: github_actions
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}